version: 0.1
sites:
  thedynastyba:
    url: "https://thedynastyba.com/"
    path: "/listings"
    target:
      name: "listings"
      pagination:
        method: "exists"
        selector: ".next"
        strategy: "locator"
      container:
        selector: ".listing-card"
        strategy: "locator"
        elements:
          title:
            selector: ".listing-name"
            strategy: "locator"
            value:
              type: "text"
              value: ""
          href:
            selector: "View Details"
            strategy: "title"
            value:
              type: "attribute"
              value: "href"
  tworld:
    url: "https://www.tworld.com/"
    path: "/buy-a-business/business-listing-search"
    target:
      name: "listings"
      pagination:
        method: "exists"
        selector: ">"
        strategy: "text"
        nth: 1
      container:
        selector: ".listing-card"
        strategy: "locator"
        elements:
          title:
            selector: ".listing-name"
            strategy: "locator"
            value:
              type: "text"
              value: ""
          href:
            selector: "View Details"
            strategy: "title"
            value:
              type: "attribute"
              value: "href"
  sunbeltnetwork:
    url: "https://www.sunbeltnetwork.com/"
    path: "/business-search/business-results"
    target:
      name: "listings"
      pagination:
        method: "enabled"
        selector: ".pagination__next"
        strategy: "locator"
      container:
        selector: ".latestBusinesses__item"
        strategy: "locator"
        elements:
          title:
            selector: ".latestBusinesses__item--title"
            strategy: "locator"
            value:
              type: "text"
              value: ""
          href:
            selector: ".latestBusinesses__item--rightButton"
            strategy: "locator"
            filter: "visible"
            value:
              type: "attribute"
              value: "href"
